[package]
name = "rust_lua_kv_db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
# Deixamos mlua já declarado para futura integração (mesmo antes de usar) – objetivo acadêmico do projeto.
mlua = { version = "0.8", features = ["lua54", "vendored" ] }